Implements "format" option to show type "trans" as it is already in the list type "trans"
sonata-project/SonataAdminBundle pull request #5578
Opened 2019-06-07 07:54 UTC by scuben

## Implements `format` option to show type `trans` as it is already in the list type `trans`

This PR implements the same behaviour for show_trans as it is available in list_trans (format option).

I am targeting this branch, because it is a NON BC feature.

## Changelog

```markdown
### Added
- Added `format` option to show type `trans`
```

2019-06-07 20:05 UTC, greg0ire commented
> NON BC feature

Non BC-breaking?

2019-06-07 20:08 UTC, greg0ire submitted a review, later dismissed

2019-06-07 20:56 UTC, scuben commented
I meant non breaking change feature 😊

2019-06-08 07:11 UTC, OskarStark requested changes
In general 👍🏻

2019-06-08 07:11 UTC, OskarStark commented on src/Resources/views/CRUD/show_trans.html.twig
> +    {% set valueFormat = field_description.options.format|default('%s') %}
Please use snake case for the variable

2019-07-03 11:21 UTC, scuben commented on src/Resources/views/CRUD/show_trans.html.twig
> +    {% set valueFormat = field_description.options.format|default('%s') %}
done

2019-07-03 11:22 UTC, scuben commented
I've changed the variable to snake_case and also did the same in the `list_trans.html.twig`. Newly added is the default translations domain taken form the admin translation domain (as it is in `list_trans.html.twig`).

2019-07-03 19:02 UTC, greg0ire submitted a review, later dismissed
Are there no docs that need to be updated?

2019-07-03 20:28 UTC, scuben commented
I've updated the docs to mention both options for list_trans and show_trans.

2019-07-03 20:35 UTC, greg0ire approved these changes

2019-07-03 23:26 UTC, phansys approved these changes

2019-07-08 05:36 UTC, OskarStark approved these changes

2019-07-08 05:36 UTC, merged

2019-07-08 05:37 UTC, OskarStark commented
Thank you 🙏