Add missed PHPDoc blocks to AbstractAdmin and related interfaces
sonata-project/SonataAdminBundle pull request #6354
Opened 2020-08-31 08:20 UTC by koninka

Classes and interfaces:
- AbstractAdmin
- AdminInterface
- UrlGeneratorInterface

## Subject

I am targeting this branch, because I want to get more well-documented code. It's good practice to document code.

2020-08-31 08:26 UTC, VincentLanglet reviewed
Thanks for your contribution.

Adding php-doc is a good practice indeed.
But it's only useful if it adds extra informations. IMHO

2020-08-31 08:26 UTC, VincentLanglet commented on src/Admin/AbstractAdmin.php
> +     */
We recently removed all the inheritdoc we found.

This does not add any useful information, this is the default behavior of phpdoc

2020-08-31 08:26 UTC, VincentLanglet commented on src/Admin/AdminInterface.php
> +     */
The typehint `self $admin` is enough to me.

2020-08-31 08:26 UTC, VincentLanglet commented on src/Admin/UrlGeneratorInterface.php
> +     */
This adds nothing. This is basically the name of the method.

2020-08-31 10:34 UTC, core23 requested changes

2020-08-31 10:34 UTC, core23 commented on src/Admin/AbstractAdmin.php
> +     * @var array
Can you add more type information like key and value types

2020-08-31 10:34 UTC, core23 commented on src/Admin/AbstractAdmin.php
> +     * @param FormMapper $form Object for simulating Form API
This comment does not add any value

2020-09-04 14:07 UTC, core23 commented
Thanks @koninka 

I merged your changes into this PR https://github.com/sonata-project/SonataAdminBundle/pull/6361

2020-09-04 14:07 UTC, closed without merging