allow symfony/console ^5.1
sonata-project/SonataAdminBundle pull request #6374
Opened 2020-09-04 19:44 UTC by dmaicher

## Subject

Allow using `symfony/console ^5.1` as it should be fully compatible.

The only relevant BC break was fixed already:
> Removed support for returning null from Command::execute(), return 0 instead

See https://github.com/symfony/symfony/blob/master/UPGRADE-5.0.md#console

## Changelog

```markdown
### Added
- Added support for `symfony/console ^5.1`
```

2020-09-04 19:50 UTC, wbloszyk approved these changes

2020-09-04 21:02 UTC, jordisala1991 requested changes
5.1 is not being installed

2020-09-05 06:21 UTC, OskarStark commented
What do you mean @jordisala1991 ?

2020-09-05 06:22 UTC, jordisala1991 commented
I just look at github actions check, for the log of composer and I dont see the console is being installed at 5.1 version on any check

2020-09-05 06:22 UTC, jordisala1991 commented
Probably because the manual merge needs to be done before this PR

2020-09-05 22:24 UTC, SonataCI commented
Could you please rebase your PR and fix merge conflicts?

2020-09-08 12:48 UTC, dmaicher commented
Yeah it cannot be installed yet due to a "conflicts" with `symfony/event-dispatcher <4.3|>=5`. So closing for now I guess.

2020-09-08 12:48 UTC, closed without merging