[POC] Csrf token util
sonata-project/SonataAdminBundle pull request #6477
Opened 2020-10-12 08:32 UTC by wbloszyk

## Subject

IMO some of functionality should be hide (from methods) to seperate service (like util). It will be nice to do it before #6472 and inject this util  there.

I am targeting this branch, because it is BC-BREAK.

## Changelog

```markdown
### Added
- Added some `Class::newMethod()` to do great stuff.

### Changed

### Deprecated

### Removed

### Fixed

### Security
```

## To do

- [ ] Update the tests
- [ ] Update the documentation
- [ ] Add an upgrade note

2020-10-20 19:21 UTC, core23 requested changes

2020-10-20 19:21 UTC, core23 commented on src/Util/CsrfTokenManager.php
> +namespace Sonata\AdminBundle\Util;
I don't like the `util` name, please try to find a more specific name for this. 

Helper, util, manager, service, ... are components that have no specific purpose and will result in god objects.

2020-10-20 19:21 UTC, core23 commented on src/Resources/config/util.php
> +        ->set('sonata.admin.util.csrf.manager', '%sonata.admin.util.csrf.generator.class%')
We should use interface names instead of named services, if we can

2020-10-20 19:21 UTC, core23 commented on src/Resources/config/util.php
> +        ->set('sonata.admin.util.csrf.generator.class', CsrfTokenManager::class)
We try to remove all `.class` parameters

2020-10-20 19:21 UTC, core23 commented on src/Util/CsrfTokenManagerInterface.php
> +    public function getCsrfToken(string $intention);
return type missing

2021-03-21 19:24 UTC, SonataCI commented
Could you please rebase your PR and fix merge conflicts?

2021-05-29 11:51 UTC, SonataCI commented
Could you please rebase your PR and fix merge conflicts?

2021-09-11 14:03 UTC, VincentLanglet commented
Closing since 4.x is the new stable branch

2021-09-11 14:03 UTC, closed without merging