[Util] Add type hints to files in Util directory
sonata-project/SonataAdminBundle pull request #6533
Opened 2020-10-23 15:03 UTC by tambait

## Subject

This is a follow up of #6404 to add param & return type hints.

## Changelog

```markdown
### Added
- Added parameter and return type hints to files in the Util directory

2020-10-23 15:47 UTC, tambait commented
Currently tests are failing because of [#L78](https://github.com/sonata-project/SonataAdminBundle/pull/6533/files#diff-743b4f55ec26cc7163d9150b5f5e8f1b40a0fbd4338f84b36dc2067ab3507b98R78). I see in jordisala1991 PR that second parameter is removed. Also, on  [#L72](https://github.com/sonata-project/SonataAdminBundle/pull/6366/files#diff-24108e2c6c473510b1c08704b623a040f7ecfa63f5fb98388072c98df357e0c9L72) he replaced AclInterface for MutableAclInterface. Can I assume it's safe to implement those and other changes from his PR into this PR?

2020-10-23 15:55 UTC, VincentLanglet commented
IMHO:
```
public function getChildren()
    {
        return new self($this->current());
    }
```

Is correct

2020-10-23 15:56 UTC, VincentLanglet commented
And the change of AclInterface to MutableAclInterface is ok.

2020-10-23 15:57 UTC, VincentLanglet commented
I would assume that all his change are ok. I will still review your full PR anyway ;)

2020-10-26 08:51 UTC, VincentLanglet commented on src/Util/AdminObjectAclData.php
> -     *
We generally add a line between different tag category, like  `@foo` et `@phpstan-foo`

2020-10-26 08:51 UTC, VincentLanglet commented on src/Util/AdminObjectAclData.php
>       * Gets admin.
Comment is useless

2020-10-26 08:51 UTC, VincentLanglet commented on src/Util/AdminObjectAclData.php
>       * Gets object.
Same

2020-10-26 08:51 UTC, VincentLanglet commented on src/Util/AdminObjectAclData.php
>       * Gets ACL users.
Same

2020-10-26 08:51 UTC, VincentLanglet commented on src/Util/AdminObjectAclData.php
>       * Sets ACL.
Same

2020-10-26 08:51 UTC, VincentLanglet commented on src/Util/AdminObjectAclData.php
>       * Gets ACL.
Same

2020-10-26 08:51 UTC, VincentLanglet commented on src/Util/AdminObjectAclData.php
> +        \assert(null !== $this->acl);
We can't assert that `this->acl` is not null.

So I would update the return type to `?MutableAclInterface`

2020-10-26 08:51 UTC, VincentLanglet commented on src/Util/AdminObjectAclData.php
>       *
`Gets masks.` is useless

2020-10-26 08:51 UTC, VincentLanglet commented on src/Util/AdminObjectAclData.php
>       *
The full comment is useless

2020-10-26 08:51 UTC, VincentLanglet commented on src/Util/AdminObjectAclData.php
> +        \assert(null !== $this->aclUsersForm);
Same, there is no argument for this assert ; so I would update the return type instead.

2020-10-26 08:51 UTC, VincentLanglet commented on src/Util/AdminObjectAclData.php
>       * Gets ACL users form.
Useless comment

2020-10-26 08:51 UTC, VincentLanglet commented on src/Util/AdminObjectAclData.php
>       *
The full comment is useless

2020-10-26 08:51 UTC, VincentLanglet commented on src/Util/AdminObjectAclData.php
>       * Gets ACL roles form.
Useless comment

2020-10-26 08:51 UTC, VincentLanglet commented on src/Util/AdminObjectAclData.php
>       * Gets permissions.
Useless comment

2020-10-26 08:51 UTC, VincentLanglet commented on src/Util/AdminObjectAclData.php
>       * Gets security handler.
Useless comment

2020-10-26 08:51 UTC, VincentLanglet commented on src/Util/AdminObjectAclManipulator.php
>       * Gets mask builder class name.
Same, could you remove the comment useless of this class

When the method is `getFooBar`, a comment `Gets foo bar` has no interest.

2020-10-26 08:51 UTC, VincentLanglet commented on src/Util/AdminObjectAclManipulator.php
>      /**
The method `protected function getSecurityIdentity($aclValue)` could return SecurityIdentityInterface instead of the current return type.

2020-10-26 08:51 UTC, VincentLanglet commented on src/Util/FormBuilderIterator.php
>      public function __construct(FormBuilderInterface $formBuilder, $prefix = false)
We should change the default value to `null` in order to type `?string`

2020-10-26 14:58 UTC, phansys requested changes

2020-10-26 14:58 UTC, phansys commented on src/Util/FormBuilderIterator.php
> +        $this->prefix = null !== $prefix ? $prefix : $formBuilder->getName();
```suggestion
        $this->prefix = $prefix ?? $formBuilder->getName();
```

2020-10-26 16:20 UTC, VincentLanglet approved these changes

2020-10-26 17:33 UTC, phansys approved these changes

2020-10-26 17:44 UTC, merged

2020-10-26 17:48 UTC, VincentLanglet commented
Thanks