Add null check before calling the id method
sonata-project/SonataAdminBundle pull request #6578
Opened 2020-11-07 21:57 UTC by VincentLanglet

## Subject

In next major only object will be allowed
I am targeting this branch, because BC.

Related to discussion: https://github.com/sonata-project/SonataAdminBundle/pull/6573#discussion_r519220677

Seems Pedantic to me.

2020-11-08 14:20 UTC, phansys requested changes

2020-11-08 14:20 UTC, phansys commented on src/Resources/views/CRUD/Association/edit_many_to_one.html.twig
> +                {% if sonata_admin.value and sonata_admin.field_description.associationadmin.id(sonata_admin.value) %}
```suggestion
                {% if sonata_admin.value and sonata_admin.field_description.associationadmin.id(sonata_admin.value) is not null %}
```

2020-11-08 14:20 UTC, phansys commented on src/Resources/views/CRUD/Association/edit_one_to_one.html.twig
> +                {% if sonata_admin.value and sonata_admin.field_description.associationadmin.id(sonata_admin.value) %}
```suggestion
                {% if sonata_admin.value and sonata_admin.field_description.associationadmin.id(sonata_admin.value) is not null %}
```

2020-11-08 14:20 UTC, phansys commented on src/Resources/views/CRUD/Association/list_one_to_one.html.twig
> +            and field_description.associationadmin.id(value)
```suggestion
            and field_description.associationadmin.id(value) is not null
```

2020-11-08 14:20 UTC, phansys commented on src/Resources/views/CRUD/Association/show_one_to_one.html.twig
> +            and field_description.associationadmin.id(value)
```suggestion
            and field_description.associationadmin.id(value) is not null
```

2020-11-08 17:33 UTC, VincentLanglet commented
Done @phansys

2020-11-08 18:20 UTC, core23 approved these changes

2020-11-09 00:36 UTC, phansys approved these changes

2020-11-09 08:57 UTC, merged