Add AdminInterface::getRoute
sonata-project/SonataAdminBundle pull request #6776
Opened 2021-01-15 16:11 UTC by VincentLanglet

## Subject

I am targeting this branch, because {reason}.

Closes #{put_issue_number_here}.

## Changelog

```markdown
### Added
- Added some `Class::newMethod()` to do great stuff.

### Changed

### Deprecated

### Removed

### Fixed

### Security
```

2021-01-22 12:19 UTC, VincentLanglet commented
Friendly ping @sonata-project/contributors :)

2021-01-22 13:15 UTC, OskarStark approved these changes

2021-01-22 17:46 UTC, franmomu commented
Should be added to `RouteCollectionInterface`?

2021-01-22 22:16 UTC, VincentLanglet commented
> Should be added to `RouteCollectionInterface`?

Yes indeed, added.

2021-01-24 08:38 UTC, OskarStark requested changes

2021-01-24 08:38 UTC, OskarStark commented on src/Route/RouteCollectionInterface.php
> +    // NEXT_MAJOR: Uncomment the following line.
```suggestion
    // NEXT_MAJOR: Uncomment the following line and remove corresponding @method annotation.
```

2021-01-24 11:49 UTC, VincentLanglet commented on src/Route/RouteCollectionInterface.php
> +    // NEXT_MAJOR: Uncomment the following line.
Done

2021-01-24 14:27 UTC, franmomu approved these changes

2021-01-25 10:35 UTC, greg0ire approved these changes

2021-01-25 10:38 UTC, VincentLanglet commented
Please take a look @OskarStark :) (Or you can dismiss the review @greg0ire, since the change asked was made)

2021-01-25 10:41 UTC, merged

2021-01-25 10:41 UTC, greg0ire commented
Thanks @VincentLanglet!