Clean up the way `required` => false is set
sonata-project/SonataAdminBundle pull request #6828
Opened 2021-01-31 13:28 UTC by VincentLanglet

## Subject

I am targeting this branch, because BC-break.

`DatagridMapper::add` used a nullable `$fieldOptions` param in order to default to `['required' => false]` thanks to 
```
    public function getFieldOptions()
    {
        return $this->getOption('field_options', ['required' => false]);
    }
```
But this is not needed for two reasons:
- The persistence bundle is already adding this option: https://github.com/sonata-project/SonataDoctrineORMAdminBundle/blob/3.x/src/Builder/DatagridBuilder.php#L179
- The Filter are already adding this option: https://github.com/sonata-project/SonataAdminBundle/blob/3.x/src/Form/Type/Filter/ChoiceType.php#L81

I also added this option to the filter which didn't have like `DateRangeType`, even if it's not needed https://github.com/sonata-project/form-extensions/blob/1.x/src/Type/DateRangeType.php#L44 but just in case the default behavior change (for example we could use `array_merge(['required' => $options['required'], $options['field_options'], $options['field_options_start'])` one day).

Closes https://github.com/sonata-project/SonataAdminBundle/issues/6272.

## Changelog

```markdown
### Changed
- Restrict `DatagridMapper::add` fifth type param to array
```

2021-01-31 13:40 UTC, VincentLanglet commented
I got an issue with phpstan
```
$mapper->add($this->getParentAssociationMapping(), null, [
                'show_filter' => false,
                'label' => false,
                'field_type' => ModelHiddenType::class,
                'field_options' => [
                    'model_manager' => $this->getModelManager(),
                ],
                'operator_type' => HiddenType::class,
            ], null, null, [
                'admin_code' => $this->getParent()->getCode(),
            ]);
```

Which let me think about what if someone write
```
$mapper->add($this->getParentAssociationMapping(), null, [
                'show_filter' => false,
                'label' => false,
                'field_type' => ModelHiddenType::class,
                'field_options' => [
                    'model_manager' => $this->getModelManager(),
                ],
                'operator_type' => HiddenType::class,
            ],Foo::class, ['foo' => 'bar'], [
                'admin_code' => $this->getParent()->getCode(),
            ]);
```
Previous to my change, it would be the same than
```
$mapper->add($this->getParentAssociationMapping(), null, [
                'show_filter' => false,
                'label' => false,
                'field_type' => Foo::class
                'field_options' => [
                    'foo' => 'bar',
                ],
                'operator_type' => HiddenType::class,
            ], null, null, [
                'admin_code' => $this->getParent()->getCode(),
            ]);
```
Does it sounds natural to you that the field_type and field_options are overriden @sonata-project/contributors ?

Should we use an array merge for the `field_options` ?

Should we deprecate the two param `$fieldType = null, array $fieldOptions = [],` in order to avoid having two way of setting the same thing ? I start to think that could be the best solution.

2021-02-09 12:54 UTC, SonataCI commented
Could you please rebase your PR and fix merge conflicts?

2021-02-09 22:36 UTC, phansys requested changes

2021-02-09 22:36 UTC, phansys commented on src/Form/Type/Filter/DateRangeType.php
> +            ->add('value', $options['field_type'], array_merge(['required' => false], $options['field_options']))
```suggestion
            ->add('value', $options['field_type'], $options['field_options'] + ['required' => false])
```

2021-02-09 22:36 UTC, phansys commented on src/Form/Type/Filter/DateTimeRangeType.php
> +            ->add('value', $options['field_type'], array_merge(['required' => false], $options['field_options']))
```suggestion
            ->add('value', $options['field_type'], $options['field_options'] + ['required' => false])
```

2021-02-09 23:04 UTC, VincentLanglet commented
Done @phansys

2021-02-09 23:17 UTC, phansys approved these changes

2021-02-10 05:52 UTC, OskarStark approved these changes

2021-02-10 08:00 UTC, merged