Add a configurePersistentParameters method
sonata-project/SonataAdminBundle pull request #6873
Opened 2021-02-16 22:16 UTC by VincentLanglet

## Subject

This allow to declare `getPersistentParameters` as final.

This prevents the developer to override incorrectly the method and loosing the benefit of the extensions.
For instance, if you look at the doc I updated, the override was losing the code.
```
        foreach ($this->getExtensions() as $extension) {
                $params = $extension->getPersistentParameters($this);

                // NEXT_MAJOR: Remove this check, since return typehint is added
                if (!\is_array($params)) {
                    throw new \RuntimeException(sprintf(
                        'The %s::getPersistentParameters must return an array',
                        \get_class($extension)
                    ));
                }

                $parameters = array_merge($parameters, $params);
        }
```

Plus it add consistency: You want to override somethings ? Use the protected method `configure*`.

## Changelog

```markdown
### Added
- `AbstractAdmin::configurePersistentParameters()`
- `AdminExtensionInterface::configurePersistentParameters()`

### Deprecated
- Overriding `AbstractAdmin::getPersistentParameters()`
- `AdminExtensionInterface::getPersistentParameters()`
```

2021-02-16 23:47 UTC, phansys requested changes

2021-02-16 23:47 UTC, phansys commented on docs/reference/routing.rst
> +template or doing other weird hacks, you can define a ``configurePersistentParameters``
```suggestion
template or doing other weird hacks, you can define a ``configurePersistentParameters()``
```

2021-02-16 23:47 UTC, phansys commented on src/Admin/AbstractAdmin.php
> +                        'The %s::getPersistentParameters must return an array',
```suggestion
                        'Method "%s::getPersistentParameters()" must return an array,',
```

2021-02-16 23:47 UTC, phansys commented on docs/reference/routing.rst
> +        public function configurePersistentParameters()
```suggestion
        public function configurePersistentParameters(): array
```

2021-02-17 00:28 UTC, phansys approved these changes

2021-02-17 09:45 UTC, wbloszyk approved these changes

2021-02-18 00:54 UTC, merged

2021-03-04 20:42 UTC, core23 commented on src/Admin/AdminExtensionInterface.php
> + * @method array configurePersistentParameters(AdminInterface $admin, array $parameters)
This causes some deprecation warnings, because the `AbstractAdminExtension` does not provide this method @VincentLanglet