[Doc] Fixed some minor syntax issues
sonata-project/SonataAdminBundle pull request #6908
Opened 2021-03-03 14:04 UTC by javiereguiluz

Just some minor fixes found while reviewing the docs. Cheers!

2021-03-03 14:06 UTC, VincentLanglet commented on docs/cookbook/recipe_custom_action.rst
> +If you want to add the current filter parameters to the redirect url you can add them to the ``generateUrl`` method::
@OskarStark Is there a linter rule for this ?

2021-03-07 22:09 UTC, phansys requested changes

2021-03-07 22:09 UTC, phansys commented on docs/cookbook/recipe_custom_action.rst
> +If you want to add the current filter parameters to the redirect url you can add them to the ``generateUrl`` method::
```suggestion
If you want to add the current filter parameters to the redirect url you can add them to the ``generateUrl()`` method::
```

2021-03-07 22:09 UTC, phansys commented on docs/reference/advanced_configuration.rst
> +The link will still appear unless you manually check it using the ``hasAccess`` method::
```suggestion
The link will still appear unless you manually check it using the ``hasAccess()`` method::
```

2021-03-08 18:10 UTC, jordisala1991 approved these changes

2021-03-08 18:10 UTC, merged

2021-03-08 18:10 UTC, jordisala1991 commented
Thank you @javiereguiluz