add extension point to configure/modify filter parameters
sonata-project/SonataAdminBundle pull request #6922
Opened 2021-03-07 21:02 UTC by dmaicher

## Subject

I am targeting this branch, because its BC.

Closes https://github.com/sonata-project/SonataAdminBundle/issues/6921

## Changelog

```markdown
### Added
- Added extension point `AbstractAdmin::configureFilterParameters` to configure/modify filter parameters
```

2021-03-07 21:27 UTC, VincentLanglet commented
Should we add the same method to `AdminExtensionInterface` and `AbstractAdminExtension` ?

2021-03-08 08:03 UTC, core23 requested changes

2021-03-08 08:03 UTC, core23 commented on src/Admin/AbstractAdmin.php
> +    protected function configureFilterParameters(array $parameters): array
Can you please add some more type information here

2021-03-08 09:43 UTC, VincentLanglet approved these changes

2021-03-08 09:50 UTC, dmaicher commented on src/Admin/AdminExtensionInterface.php
> +    //public function configureFilterParameters(array $parameters): array;
@VincentLanglet added this

2021-03-08 09:51 UTC, VincentLanglet approved these changes

2021-03-08 09:59 UTC, core23 approved these changes

2021-03-08 10:02 UTC, core23 approved these changes

2021-03-08 10:08 UTC, merged