Simulate a reset of filters if no values are different from the default ones
sonata-project/SonataAdminBundle pull request #7254
Opened 2021-06-13 11:56 UTC by VincentLanglet

## Subject

I am targeting this branch, because patch.

Closes #7250.

## Changelog

```markdown
### Fixed
- Filter are correctly updated if only default values are submitted.
```

2021-06-13 12:03 UTC, kirya-dev commented
Hello!
Im dont thinking that this is good solution

2021-06-13 12:07 UTC, kirya-dev commented
@VincentLanglet you can provide short screen cast with problem? (gif)

2021-06-13 12:14 UTC, VincentLanglet commented
Default situation: 
![image](https://user-images.githubusercontent.com/9052536/121806638-f6808580-cc50-11eb-929a-3553dbcf97be.png)

I change a filter and submit
![image](https://user-images.githubusercontent.com/9052536/121806698-38113080-cc51-11eb-9a3d-c0d91d5a6949.png)

I remove the filter manually
![image](https://user-images.githubusercontent.com/9052536/121806705-43fcf280-cc51-11eb-9abf-fda7364d7a7e.png)
Then if I submit it comes back
![image](https://user-images.githubusercontent.com/9052536/121806722-55de9580-cc51-11eb-936d-466b140b76dc.png)

Because no filter are submitted so if you use filter persisters, you have this code 
```
                // if reset filters is asked, remove from storage
                if ('reset' === $this->getRequest()->query->get('filters')) {
                    $this->getFilterPersister()->reset($this->getCode());
                }

                // if no filters, fetch from storage
                // otherwise save to storage
                if (empty($filters)) {
                    $filters = $this->getFilterPersister()->get($this->getCode());
                } else {
                    $this->getFilterPersister()->set($this->getCode(), $filters);
                }
```
And i'm inside the `if (empty($filters)) {` case.

By simulating the reset, it solve the issue. I tried this code on my project.

2021-06-13 12:34 UTC, kirya-dev commented
Im think problem in backend side

2021-06-13 12:36 UTC, kirya-dev commented
You can provide url on each step?

2021-06-13 12:58 UTC, VincentLanglet commented
First time I come
```
http://10.0.0.8/index.php/asv/admin/assurancevie/contract-operation-subscription/list?checkConsistency=
```
When I submit a new filter
```
http://10.0.0.8/index.php/asv/admin/assurancevie/contract-operation-subscription/list?filter%5BprocessedStatus%5D%5Bvalue%5D=operation.status.processed&checkConsistency=
```
When I remove the filter submitted (so I want to go back to the default values)
```
http://10.0.0.8/index.php/asv/admin/assurancevie/contract-operation-subscription/list?checkConsistency=
```
But the filter wasn't removed.

I don't think it's a backend issue. Because if after the url 
```
http://10.0.0.8/index.php/asv/admin/assurancevie/contract-operation-subscription/list?filter%5BprocessedStatus%5D%5Bvalue%5D=operation.status.processed&checkConsistency=
```
I would have go to another admin: 
```
http://10.0.0.8/index.php/asv/admin/assurancevie/contract/list
```
And then back to the initial admin
```
http://10.0.0.8/index.php/asv/admin/assurancevie/contract-operation-subscription/list?checkConsistency=
```
The behavior is the one wanted, both filter are still filled, since I'm persisting the filter in the session.

The issue here is that if you submit no filter, the session is not updated.
There is nothing in the request saying that an empty submit has been done. So the admin cannot determine if we're loading the admin page from another page or not. That's why the only solution seems to add `filters=reset`

2021-06-13 13:26 UTC, kirya-dev commented
Removed filter come back?

2021-06-13 13:28 UTC, VincentLanglet commented
> Removed filter come back?

When I remove the value of a filter (and there is only the default value) and click on submit, yes it came back.
Because the url is `http://10.0.0.8/index.php/asv/admin/assurancevie/contract-operation-subscription/list?checkConsistency=`
And the persisterFilter use the filter of the session.

2021-06-13 19:46 UTC, kirya-dev commented
How correctly change default filters via session?
It seems FilterPersister is extra feature...
Or we can redirect to correct link if has persisted values on link with persisted params ?

2021-06-13 19:54 UTC, VincentLanglet commented
> How correctly change default filters via session?

IMHO, that's the correct way.
I want to submit the default value, either i add them in the url, either I set `filters=reset`.

So if you want to keep the feature which remove default value from the url, `filters=reset` is the solution.

There is a front hack to not fully submit the filter form, so it's a front bug, with a front fix.
The back end shouldn't be modified.

2021-06-13 20:05 UTC, kirya-dev commented
Hmm. You solution can be exists)

Me seams will shorter change type of reset button to hidden to submit

2021-06-13 23:22 UTC, phansys requested changes

2021-06-13 23:22 UTC, phansys commented on src/Resources/public/Admin.js
> +                field.attr("name", 'filters').attr("type","hidden");
Just for consistency:
```suggestion
                field.attr('name', 'filters').attr('type', 'hidden');
```

2021-06-13 23:38 UTC, VincentLanglet commented on src/Resources/public/Admin.js
> +                field.attr("name", 'filters').attr("type","hidden");
Sure, done

2021-06-14 00:09 UTC, phansys approved these changes

2021-06-14 05:31 UTC, kirya-dev commented
I have an idea, what else getDefaultFilterParameters must return merged params with persistFilter?

2021-06-14 06:25 UTC, VincentLanglet commented
> I have an idea, what else getDefaultFilterParameters must return merged params with persistFilter?

I don't see how it solve the issue and I don't think it's a good idea.
This would say `getDefaultFilterParameters` will change with the request.
I expect a `getDefault` method to always return the same result.

2021-06-14 10:24 UTC, kirya-dev commented
> This would say getDefaultFilterParameters will change with the request.

No. In my idea `getDefaultFilterParameters` must only merge. Dont reset or set.

2021-06-14 10:26 UTC, VincentLanglet commented
> > This would say getDefaultFilterParameters will change with the request.
> 
> No. In my idea `getDefaultFilterParameters` must only merge. Dont reset or set.

This is already the case.

2021-06-14 10:35 UTC, kirya-dev commented
> This is already the case
Can show me this?

2021-06-14 10:40 UTC, VincentLanglet commented
> I see this in master

Yes, so it's only a merge.

> In my idea getDefaultFilterParameters must only merge

2021-06-15 23:45 UTC, phansys submitted a review, later dismissed

2021-06-15 23:45 UTC, phansys commented on src/Resources/public/Admin.js
> +                var field = $(document.createElement("input"));
```suggestion
                var field = $(document.createElement('input'));
```

2021-06-16 09:45 UTC, phansys requested changes

2021-06-16 09:45 UTC, phansys commented on src/Resources/public/Admin.js
> +                var field = $(document.createElement('input'));
```suggestion
                var field = jQuery(document.createElement('input'));
```
See #7262.

2021-06-16 09:45 UTC, phansys commented on src/Resources/public/Admin.js
> +                if (JSON.stringify(defaults[field.name] || defaultValue) === JSON.stringify($(field).val() || defaultValue)) {
```suggestion
                if (JSON.stringify(defaults[field.name] || defaultValue) === JSON.stringify(jQuery(field).val() || defaultValue)) {
```

2021-06-16 11:40 UTC, kirya-dev commented on src/Resources/public/Admin.js
> +                var field = $(document.createElement('input'));
All this method can be replace by 
```js
$form.append('<input type="filters" type="hidden" value="reset">');
```

2021-06-16 15:51 UTC, SonataCI commented
Could you please rebase your PR and fix merge conflicts?

2021-06-16 17:16 UTC, VincentLanglet commented on src/Resources/public/Admin.js
> +                var field = $(document.createElement('input'));
Done

2021-06-16 17:16 UTC, VincentLanglet commented on src/Resources/public/Admin.js
> +                if (JSON.stringify(defaults[field.name] || defaultValue) === JSON.stringify($(field).val() || defaultValue)) {
Done

2021-06-16 18:00 UTC, jordisala1991 commented
Imo we should try to not introduce more jquery, can you provide a vanilla javascript implementation?

2021-06-16 18:04 UTC, VincentLanglet commented
> Imo we should try to not introduce more jquery, can you provide a vanilla javascript implementation?

I'm not really introducing jquery here. I'm
- Fixing the `if (JSON.stringify(defaults[field.name] || '') === JSON.stringify(jQuery(field).val())) {` code.
- Adding call on an already existing variable `$form`.

Rewriting my code with vanilla JS would only make sens if I rewrite the whole function without Jquery.
It's a lot of extra-work for a bug-fix.
And since I don't work a lot with JS, especially vanilla, I would take me a lot of time and I cannot promise it will still work.
So I'd rather not to do this.

2021-06-16 21:29 UTC, phansys approved these changes

2021-06-16 21:46 UTC, kirya-dev commented
Its can usefull to you
https://gist.github.com/joyrexus/7307312

2021-06-24 20:09 UTC, VincentLanglet commented
Can we merge this @sonata-project/contributors ?

2021-06-28 13:24 UTC, merged