Only use one array for the option of DatagridMapper
sonata-project/SonataAdminBundle pull request #7258
Opened 2021-06-14 00:46 UTC by VincentLanglet

## Subject

When working on https://github.com/sonata-project/SonataAdminBundle/pull/7257, I discovered we have $filterOptions and $fieldDescriptions which does pretty the same things for the DatagridMapper. They are merged half the time, the filterOptions is passed to a field description (which is weird because we could expect the passed one is the fieldDescriptionOptions), ...

I think we can merge the two options.

I am targeting this branch, because I just added a deprecation.

## Changelog

```markdown
### Deprecated
- Passing more than 3 arguments to `DatagridMapper::add()` method.
```

2021-06-14 05:52 UTC, franmomu requested changes
IMO this is wrong, if these parameters are merged I think we should solve that, otherwise we have a big ball of mud not knowing what is needed for a filter or for `FieldDescriptionOptions`.

To me, we should do has we do in `FormMapper` for all mappers (as it is right now also in `DatagridMapper`) that we have an array for configuring the type we are adding (the filter in this case) and another one for `FieldDescriptionOptions`.

2021-06-14 06:16 UTC, VincentLanglet commented
We introduce a FieldDescriptionType:
```
 * @phpstan-type FieldDescriptionOptions = array{
 *  accessor?: string|callable|\Symfony\Component\PropertyAccess\PropertyPathInterface,
 *  associated_property?: string|callable|\Symfony\Component\PropertyAccess\PropertyPathInterface,
 *  label?: string|false|null,
 *  link_parameters?: array<string, mixed>,
 *  role?: string|string[],
 *  sort_field_mapping?: array<string, mixed>,
 *  sort_parent_association_mappings?: array<array<string, mixed>>,
 *  sortable?: string|bool,
 *  template?: string,
 *  translation_domain?: string,
 *  type?: string,
 *  virtual_field?: bool
 * }&array<string, mixed>
```

All these values are passed to the ShowMapper/ListMapper as third argument.

In case of the DatagridMapper
- All the values except the `role` can be passed to the third argument since there is an array merge.
- If we want to restrict the field to some role, we have to provide a fourth argument.

With the code 
```
$fieldDescription->mergeOptions($filterOptions)
```
We're even promoting to pass a much as possible options to the third argument. Since both
```
->add('foo', null, ['virtual_field' => true]); 
->add('foo', null, [], ['virtual_field' => true]); 
```
works, but only
```
->add($fieldDescription, null, ['virtual_field' => true]);
```
works.

I don't think it's worth to keep the two arrays, just to separate the role.
ShowMapper and ListMapper works fine with one argument. And if you look at the code, the DatagridMapper has a really similar code, so should have a really similar signature.

The FormMapper is really different, we doing two separate add calls:
```
$fieldDescription = $this->getAdmin()->createFieldDescription(
     $name instanceof FormBuilderInterface ? $name->getName() : $name,
     $fieldDescriptionOptions
);
$this->getAdmin()->addFormFieldDescription($fieldName, $fieldDescription);
$this->formBuilder->add($child, $type, $options);
```
so you need options of the fieldDescription and options of the formBuilder.
While in other Mapper there is only the following call
```
$fieldDescription = $this->getAdmin()->createFieldDescription(
     $name,
     $fieldDescriptionOptions
);
$this->builder->addFilter($this->datagrid, $type, $fieldDescription, $this->getAdmin());
```
so you only need options for the field description.

2021-06-16 23:26 UTC, franmomu commented
I think we should keep the two arrays as it is:
- one for configuring the filter like for example [`StringFilter` in the ORM](https://github.com/sonata-project/SonataDoctrineORMAdminBundle/blob/e87c7e9af10a935decf436a15479649d31f9fd96/src/Filter/StringFilter.php#L154-L166).
- The other one for `FieldDescriptionOptions`.

Otherwise we end up with a mess of options that we don't know where they belong to, I think the problem is in the implementation if we are merging these options.

> ShowMapper and ListMapper works fine with one argument.

To me, it works, but not fine, hence the problem we've already discussed about the `&array<string, mixed>` part of `FieldDescriptionOptions`.

Ideally, to me, we should create classes for `Show` and `List`, something like for example `CurrencyType` so we could do something like:

```php
$list->add('currency', CurrencyType::class, [
    'currency' => 'EUR',
], $fieldDescriptionOptions);
```
Users could create their own:

```php
$list->add('user', UserType::class, ['mode' => 'short']);
```
Where `UserType` would define its template and other options and these options should be used to configure these types and not for `FieldDescription`.

That's why I think we should do as we do with `FormMapper`.

2021-06-16 23:54 UTC, VincentLanglet commented
> I think we should keep the two arrays as it is:
> 
> * one for configuring the filter like for example [`StringFilter` in the ORM](https://github.com/sonata-project/SonataDoctrineORMAdminBundle/blob/e87c7e9af10a935decf436a15479649d31f9fd96/src/Filter/StringFilter.php#L154-L166).
> * The other one for `FieldDescriptionOptions`.

Both are the same things. Look at the usage in the method.

If you look at the `filterOptions`, the only place it's used is here: 
https://github.com/sonata-project/SonataAdminBundle/blob/82afd8a37ef233a9b00d5751f679f9810de05a57/src/Datagrid/DatagridMapper.php#L137-L140

Then, the fieldDescription is passed to the `addFilter` method
https://github.com/sonata-project/SonataAdminBundle/blob/82afd8a37ef233a9b00d5751f679f9810de05a57/src/Datagrid/DatagridMapper.php#L162

Then the filter is created with the option of the FieldDescription: https://github.com/sonata-project/SonataDoctrineORMAdminBundle/blob/3.x/src/Builder/DatagridBuilder.php#L200

The is no differences in the code between a `filterOption` and a `fieldDescription`. So merging these is IMHO the right thing to do currently in order to
- Be transparent about the current behavior
- Having consistency with the ShowMapper and the ListMapper

The current Sonata code is not making any differences between these two arrays, let's start to be honest and merge them currently. If one day we will have a real implementation, with different usage of these, we could introduce a new param.

> $list->add('currency', CurrencyType::class, [
    'currency' => 'EUR',
], $fieldDescriptionOptions);

It would require a lot of development/BC-break. And many discussions: For instance as a user of this library, I override often the labels. With your proposal it would be
```
$list->add('currency', CurrencyType::class, [], ['label' => 'foo']);
```
It means I would have to add an extra empty array for every call I have. Plus I would lose consistency with the $form, where it's
```
$form->add('foo', TextType::class, ['label' => 'foo']);
```
An issue can be created for this.

2021-06-24 20:10 UTC, VincentLanglet commented
Please review @sonata-project/contributors

2021-06-26 18:31 UTC, franmomu commented
> The is no differences in the code between a filterOption and a fieldDescription. So merging these is IMHO the right thing to do currently in order to
> So merging these is IMHO the right thing to do currently in order to
> 
> * Be transparent about the current behavior
> * Having consistency with the ShowMapper and the ListMapper
> 
> The current Sonata code is not making any differences between these two arrays, let's start to be honest and merge them currently. If one day we will have a real implementation, with different usage of these, we could introduce a new param.

This is what I think we should tackle, `Filter` has its options and IMO we should use them instead of merging them with the ones of `FieldDescription`, differentiate them so we can check if the options passed to the filter are valid or not, so probably modifying

https://github.com/sonata-project/SonataAdminBundle/blob/82afd8a37ef233a9b00d5751f679f9810de05a57/src/Datagrid/DatagridMapper.php#L162

to allow `$filterOptions`.


`ShowMapper` and `ListMapper` don't have types yet, so `FieldDescription` is used as a DTO to send it to the view and the way to configure them is through `FieldDescription` options.

> For instance as a user of this library, I override often the labels. With your proposal it would be
> 
> ```
> $list->add('currency', CurrencyType::class, [], ['label' => 'foo']);
> ```
> 
> It means I would have to add an extra empty array for every call I have. Plus I would lose consistency with the $form, where it's
> 
> ```
> $form->add('foo', TextType::class, ['label' => 'foo']);
> ```
> 

In this case I think `label` will be an option of the `Filter` as as the $form does which I think it makes sense.

2021-06-26 20:24 UTC, VincentLanglet commented
> This is what I think we should tackle, `Filter` has its options and IMO we should use them instead of merging them with the ones of `FieldDescription`, differentiate them so we can check if the options passed to the filter are valid or not, so probably modifying
> 
> https://github.com/sonata-project/SonataAdminBundle/blob/82afd8a37ef233a9b00d5751f679f9810de05a57/src/Datagrid/DatagridMapper.php#L162
> 
> to allow `$filterOptions`.

Let's see if it would be possible.

In the implementation of the `addFilter` method, when we're guessing the type of the Filter, we're setting all the options to the fieldDescription:
https://github.com/sonata-project/SonataDoctrineORMAdminBundle/blob/3.x/src/Builder/DatagridBuilder.php#L174-L180

There is options like:
- parent_association_mappings, field_name, mapping_type which are coming from the FieldDescription and meant to be used by the filter.
- operator_type, operator_options, field_type, field_options which are used by the filter only.
So this might be useless and we may remove this code in we use a $filterOptions separately.

But then we're calling `fixFieldDescription` which is setting a lot of option to the fieldDescription:
- field_mapping
- global_search which a FilterOption
- association_mapping
- parent_association_mappings
- field_name
- adding required => false to the `field_options`
- in case of the ModelAutocompleteFilter, it merge a lot of options to the `field_options`.

The filter won't have these options anymore if we use a separate array `$filterOptions`.
FormContractorInterface has a `getDefaultOptions`, I think adding the same to the DatagridBuilderInterface could solve the problem.

Then we're calling `addFilterFieldDescription` and then
```
$filter = $this->filterFactory->create($fieldDescription->getName(), $type, $fieldDescription->getOptions());
$datagrid->addFilter($filter);
```

Can you take a look at this try @franmomu ?
https://github.com/sonata-project/SonataAdminBundle/pull/7281
https://github.com/sonata-project/SonataDoctrineORMAdminBundle/pull/1468

> > It means I would have to add an extra empty array for every call I have. Plus I would lose consistency with the $form, where it's
> > ```
> > $form->add('foo', TextType::class, ['label' => 'foo']);
> > ```
> 
> In this case I think `label` will be an option of the `Filter` as as the $form does which I think it makes sense.

Indeed, I thought it would be an issue to have a FieldDescription without a label, but in fact it's the way it works for the FormMapper.

2021-06-27 13:04 UTC, VincentLanglet commented
I will report this to 5.0

2021-06-27 13:04 UTC, closed without merging