Fix array to string conversion exception
sonata-project/SonataAdminBundle pull request #7566
Opened 2021-10-30 04:26 UTC by nhung-le

## Subject

I am targeting this branch, because I would like to make a patch to fix an issue, below is the explanation for issue:
When you use `configureDatagridFilters` and put `id` field in then filter by ID from user's POV.   The `id` field will be treated same as any other filter parameters, which will convert it into an array, so when you call back the `list` route with list of parameters it will throw an array to string exception. check attached screenshots to be clearer I hope it can makes sense, tested from our project for the behaviors, freely to change and correct if I am wrong.

Closes #{put_issue_number_here}. sorry I haven't open an issue here, it's about `Array to string conversion` exception (when putting object's id as filter parameter)

## Changelog

```markdown
### Added
- Added check if `id` is an array in AbstractAdmin->getObject()

### Changed

### Deprecated

### Removed

### Fixed
Array to string conversion exception

### Security
```

Attached screenshot for the issue (happened on our own project) :

If you put `id` in `configureDatagridFilters` -> this will call from `CRUDController->assertObjectExists() line 1311`  passing the `id` as an array into `$admin->getObject($objectId);` then encounter array to string conversion 
![request-admin-id-param](https://user-images.githubusercontent.com/64844393/139519991-a95aec45-bbb1-4ccc-81c4-81d818a84743.PNG)

2021-10-30 08:29 UTC, VincentLanglet requested changes
The id used for the filter shouldn't be used to look for an object for the admin.

To me there are different explanation of the problem:
- We're looking for an objectId for the admin, but we shouldn't for a list, or at least just looking at the parent.
- The `assertObjectExists` is calling `getObject` as long as the `objectId` is not null, without checking it's a string/int.
- As far as know, the `id` used for the admin url are parameters (which are found in the `$request->attributes` part when the `id` for the filter is in the `$request->query` part. If we stop to use `$request->get` it would avoid such conflicts. A good example/solution for https://github.com/sonata-project/SonataAdminBundle/issues/7365

I would say the `idParameters` are always in the attributes, but I'm not sure. WDYT @sonata-project/contributors.
The other option would be to change the check `if (null !== $objectId) {`

2021-10-30 13:16 UTC, phansys commented
IMO, the unique identifier for an admin's subject is always a string when retrieved from the request.
https://github.com/sonata-project/SonataAdminBundle/blob/0e8a14e4f27ebab086ea53e051f5b21e8b574691/src/Admin/AdminInterface.php#L103-L106
https://github.com/sonata-project/SonataAdminBundle/blob/0e8a14e4f27ebab086ea53e051f5b21e8b574691/src/Admin/AdminInterface.php#L120-L125
It is not a kind of filter or additional parameter.

2021-10-30 13:44 UTC, VincentLanglet commented
> It is not a kind of filter or additional parameter.

I'm not sure about it but I think he wanted to add an `id` filter on the list, and this created a conflict with the fact we're looking for an id in the url.

But it's kinda weird because I remember having some id filters...

2021-10-30 13:54 UTC, nhung-le commented
> But it's kinda weird because I remember having some id filters...

Basically it was because we redirected back to the `list` route while sending the list parameters again after our custom action. so inside our admin controller it is like this:
```php
public function enableAction(Request $requestr) {
 //  custom action happen here
 // error when redirect back to list like below, **only happen when user filter by object Id before did the action
         return new RedirectResponse($this->admin->generateUrl('list', $this->admin->getFilterParameters()));
}
```
and for how to add the `id` to list filter:
```php
protected function configureDatagridFilters(DatagridMapper $datagridMapper)
    {
        $datagridMapper
            ->add('id', null, ['global_search' => false]);
    }
```

Hope this makes sense, will make a proper issue later. thanks a lot

2021-10-30 15:44 UTC, VincentLanglet commented
I think you're doing it wrong, it's
```
new RedirectResponse($this->admin->generateUrl('list', ['filter' => $this->admin->getFilterParameters()]));
```

2021-10-30 16:12 UTC, nhung-le commented
> I think you're doing it wrong, it's
> 
> ```
> new RedirectResponse($this->admin->generateUrl('list', ['filter' => $this->admin->getFilterParameters()]));
> ```

i'm out of office now. but that sounds reallly... hit the point ! I will try and then tell you again, thanks!

2021-10-31 11:10 UTC, jordisala1991 commented
Closing , since a solution is provided. If it turns out it don't work, please open first an issue to study your case.

2021-10-31 11:10 UTC, closed without merging

2021-11-01 03:38 UTC, nhung-le commented
> I think you're doing it wrong, it's
> 
> ```
> new RedirectResponse($this->admin->generateUrl('list', ['filter' => $this->admin->getFilterParameters()]));
> ```

I came back to notify that this works by the way, thank you very much.