Fix display of enums for nullable property
sonata-project/SonataAdminBundle pull request #8091
Opened 2023-08-17 14:14 UTC by bedfir

## Subject

Same issue than previously fixed in #8039 

## Changelog

```markdown

### Fixed
- Fix display of enums for nullable property

```

2023-08-26 12:38 UTC, VincentLanglet commented
Regression was introduced here https://github.com/sonata-project/SonataAdminBundle/pull/8070 cc @phansys 

Would be great if one could add a non-regression test

2023-08-26 22:48 UTC, phansys commented
>Would be great if one could add a non-regression test

I'll try to take a look this week if it's not too late.
Thanks for pointing.

2023-08-27 21:45 UTC, phansys requested changes
Thanks for this contribution @bedfir!

2023-08-27 21:45 UTC, phansys commented on src/Resources/views/CRUD/display_enum.html.twig
> +    {% if value is null %}
In order to cover this case and avoid further regressions, please add a case at [`RenderElementExtensionTest::getRenderListElementTests()`](https://github.com/bedfir/SonataAdminBundle/blob/cf2cc488d6f9836ac3c2cc8e98906142c8aed45b/tests/Twig/Extension/RenderElementExtensionTest.php#L1541):

```php
$elements[] = [
    '<td class="sonata-ba-list-field sonata-ba-list-field-enum" objectId="12345"> &nbsp; </td>',
    FieldDescriptionInterface::TYPE_ENUM,
    null,
    [
        'use_value' => true,
    ],
];
```

2023-08-28 08:10 UTC, VincentLanglet approved these changes

2023-08-28 08:56 UTC, phansys approved these changes

2023-08-28 09:00 UTC, merged