:bug: Fix label & method countResults to display good things with simple pager
sonata-project/SonataAdminBundle pull request #8183
Opened 2024-05-15 09:46 UTC by elyanory

## Subject

Using SimplePager renders wrong statement on batch actions. 
For example: selecting 50 elements (on a table containing >1000 elements) the batch action checkbox "all_elements" would result in "all elements (51)".

Now with this PR, the display will change. A second basic query will be used to count the total number of results. 
Using the example above, this would give: "all elements (1000)".

Closes #8164.

## Changelog

```markdown
### Added
- `SimplePager::getTotalResults()` This method actually calculates the number of lines.

### Changed
- `SimplePager::countResults()` The "countResults" method now returns the true total number of lines ;
- `SimplePager::init()` The "init" method also calculates the total number of lines.

### Deprecated

### Removed

### Fixed

### Security
```

2024-05-15 12:16 UTC, zyberspace commented
But doesn't this make the simple pager super slow on huge datasets? I thought the whole reason to use the simple pager is because the count of the normal pager would take too long for certain entities?

2024-05-15 15:16 UTC, VincentLanglet requested changes
> But doesn't this make the simple pager super slow on huge datasets? I thought the whole reason to use the simple pager is because the count of the normal pager would take too long for certain entities?

Cf the doc,
https://docs.sonata-project.org/projects/SonataAdminBundle/en/4.x/cookbook/recipe_improve_performance_large_datasets/#change-default-pager-to-simplepager

This is exactly the purpose of the SimplePager. You lost every benefit with such implementation.

2024-05-15 15:16 UTC, VincentLanglet commented on src/Datagrid/SimplePager.php
> +        return $query->getDoctrineQuery()->getSingleScalarResult();
This is wrong, you're introducing a dependy on `Sonata\DoctrineORMAdminBundle` but SonataAdmin is supposed to work with any other database bundle like https://github.com/sonata-project/SonataDoctrineMongoDBAdminBundle or a custom one.

You can only use method from the ProxyQueryInterface API.

2024-05-17 10:27 UTC, elyanory commented
> But doesn't this make the simple pager super slow on huge datasets? I thought the whole reason to use the simple pager is because the count of the normal pager would take too long for certain entities?

> This is exactly the purpose of the SimplePager. You lost every benefit with such implementation.

You're right, I'm going to lean more towards the idea of displaying something like this: "25+".
I thought that adding a simple query to get the total number of results would be interesting 😉

2024-11-14 19:43 UTC, VincentLanglet commented
https://github.com/sonata-project/SonataAdminBundle/pull/8205 strategy should be preferred

2024-11-14 19:43 UTC, closed without merging