[POC] Replace x-editor
sonata-project/SonataAdminBundle pull request #8221
Opened 2024-12-07 07:57 UTC by onEXHovia

## Subject

Example of possible implementation for replacement xeditor to classic way. On the first request we create a form with an editable field and display in popover, after successfully submit form, we update the field in the list.

This is a very quick implementation to discuss, I am open to ideas and suggestions. This approach gives more flexibility than xeditable because everything is built around symfony forms.

## Changelog

```markdown
### Added

### Changed

### Deprecated

### Removed

### Fixed

### Security
```

2024-12-07 08:07 UTC, VincentLanglet commented
Can u add screenshot before/after ?
Thanks

2024-12-07 08:24 UTC, onEXHovia commented
> Can u add screenshot before/after ? Thanks

The appearance is the same as xeditable
<img width="327" alt="edit" src="https://github.com/user-attachments/assets/beb4958f-cd9d-442b-a217-274f4fa73a07">

2024-12-07 10:13 UTC, VincentLanglet reviewed
I like the idea, this would help to bump to boostrap 4 (or 5) https://github.com/sonata-project/SonataAdminBundle/issues/7156

- @sonata-project/contributors WDYT ?
- We need to decide if it requires to be releases as 5.0 or if it can be considered as BC.
- CI need to be fixed

2024-12-07 10:46 UTC, onEXHovia commented
> I like the idea, this would help to bump to boostrap 4 (or 5) #7156

My plans include updating the frontend(https://github.com/sonata-project/SonataAdminBundle/issues/7156) and replacing adminlte to bootstrap 5.*, I think all the changes should be in the release of the 5.x branch.

2024-12-07 10:58 UTC, core23 requested changes

2024-12-07 10:58 UTC, core23 commented on assets/js/admin.js
> +    return;
This is intended? Either leave a comment with a TODO or remove the code below

2024-12-07 11:03 UTC, core23 commented
> I like the idea, this would help to bump to boostrap 4 (or 5) #7156
> 
> * @sonata-project/contributors WDYT ?
> * We need to decide if it requires to be releases as 5.0 or if it can be considered as BC.
> * CI need to be fixed

We could do it in the 5.0, but this will take months or even years to be released... 

Looking at EasyAdmin, they allow minor breaking changes on stable branches, with all the downsides.  
At the moment we also have a CVE in our stable branch that could not be fixed without dropping support for bootstrap 3 / 4, which will also be a big breaking change.

2024-12-07 14:33 UTC, zyberspace commented
Hi @onEXHovia ,

thanks for the work! This is indeed an important step to get the Admin LTE working (one of many 😄 ).

*Regarding BC:*

I just looked at our more heavily modified sonata admin projects and I would prefer to have a feature flag in the `sonata_admin` config, e.g. `enable_new_editable`, that throws a deprecation if set to the default `false` value. API-Platform did this with more than one feature for the 3.x branch and the update was a breeze thanks to it. This way i was able to fix one deprecation at a time and do multiple updates until everything was fixed.

Deprecation example: https://github.com/api-platform/core/blob/3.4/src/Symfony/Bundle/DependencyInjection/ApiPlatformExtension.php#L1032-L1034

```php
->booleanNode('keep_legacy_inflector')->defaultTrue()->info('Keep doctrine/inflector instead of symfony/string to generate plurals for routes.')->end()

// ...

 if ($config['keep_legacy_inflector']) {
    trigger_deprecation('api-platform/core', '3.2', 'Using doctrine/inflector is deprecated since API Platform 3.2 and will be removed in API Platform 4. Use symfony/string instead. Run "composer require symfony/string" and set "keep_legacy_inflector" to false in config.');
}
```

*Regarding the PR itself:*

Would it be possible to add a few events to the stimulus controller to be able to modify the request options and maybe even the response? At least the options i could do via twig with the `x-editable` implementation.

Thanks!

2024-12-08 10:06 UTC, VincentLanglet commented
I think such PR can be done in 4.x
- If there is no BC break in PHP.
- If we get the same behavior in js.

I'm not sure we need to provide a `enable_new_editable` flag

2024-12-20 14:47 UTC, jordisala1991 commented on .eslintrc.js
> +    'lines-between-class-members': { 'properties': 'off', 'methods': 'always' }
this file should be edited on dev kit

2025-06-25 15:02 UTC, closed without merging